FROM ruby:3.2

# Set default locale for the environment
ENV LC_ALL C.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

WORKDIR /usr/src/app

COPY Gemfile Gemfile.lock jekyll-text-theme.gemspec ./
RUN bundle config set deployment true && bundle install

EXPOSE 4000

CMD ["bundle", "exec", "jekyll", "help"]
